export const transformedResource = {
  alternate_name: null,
  certified: false,
  email: null,
  id: 1,
  legal_status: null,
  long_description: null,
  name: 'Lyon-Martin Health Services',
  short_description: null,
  status: 'approved',
  verified_at: null,
  website: 'www.google.com',
  certified_at: null,
  featured: null,
  source_attribution: 'ask_darcel',
  services: [
    {
      alternate_name: null,
      application_process: null,
      certified: false,
      eligibility: null,
      email: null,
      fee: null,
      id: 1,
      interpretation_services: null,
      long_description: 'TB Testing, Pregnancy Test, STD Testing, STD Treatment, HIV Testing, HIV Treatment,\r\nTransgender Svcs, Immunizations, Women’s Health, Family Planning, Mental Health,\r\nPrimary Care. MediCal, MediCare, uninsured people $0-full bill. Women & all transgender welcome.',
      name: 'newname',
      required_documents: null,
      url: null,
      verified_at: null,
      wait_time: null,
      certified_at: null,
      featured: null,
      source_attribution: 'ask_darcel',
      schedule: {
        id: 1,
        schedule_days: [
          {
            id: 5,
            day: 'Friday',
            opens_at: 900,
            closes_at: 1730,
            open_time: null,
            open_day: null,
            close_time: null,
            close_day: null,
          },
          {
            id: 4,
            day: 'Thursday',
            opens_at: 900,
            closes_at: 1730,
            open_time: null,
            open_day: null,
            close_time: null,
            close_day: null,
          },
          {
            id: 3,
            day: 'Wednesday',
            opens_at: 900,
            closes_at: 1730,
            open_time: null,
            open_day: null,
            close_time: null,
            close_day: null,
          },
          {
            id: 2,
            day: 'Tuesday',
            opens_at: 1100,
            closes_at: 1930,
            open_time: null,
            open_day: null,
            close_time: null,
            close_day: null,
          },
          {
            id: 1,
            day: 'Monday',
            opens_at: 1100,
            closes_at: 1930,
            open_time: null,
            open_day: null,
            close_time: null,
            close_day: null,
          },
        ],
      },
      notes: [
        {
          id: 1,
          note: 'English & Spanish. Email: info@lyon-martin.org.',
        },
      ],
      categories: [
        {
          name: 'Medical',
          id: 3,
          top_level: true,
          featured: false,
        },
      ],
      eligibilities: [],
      recurringSchedule: {
        intervals: [
          {
            opensAt: {
              day: 1,
              hour: 11,
              minute: 0,
            },
            closesAt: {
              day: 1,
              hour: 19,
              minute: 30,
            },
          },
          {
            opensAt: {
              day: 2,
              hour: 11,
              minute: 0,
            },
            closesAt: {
              day: 2,
              hour: 19,
              minute: 30,
            },
          },
          {
            opensAt: {
              day: 3,
              hour: 9,
              minute: 0,
            },
            closesAt: {
              day: 3,
              hour: 17,
              minute: 30,
            },
          },
          {
            opensAt: {
              day: 4,
              hour: 9,
              minute: 0,
            },
            closesAt: {
              day: 4,
              hour: 17,
              minute: 30,
            },
          },
          {
            opensAt: {
              day: 5,
              hour: 9,
              minute: 0,
            },
            closesAt: {
              day: 5,
              hour: 17,
              minute: 30,
            },
          },
        ],
      },
    },
  ],
  schedule: {
    id: 1,
    schedule_days: [
      {
        id: 5,
        day: 'Friday',
        opens_at: 900,
        closes_at: 1730,
        open_time: null,
        open_day: null,
        close_time: null,
        close_day: null,
      },
      {
        id: 4,
        day: 'Thursday',
        opens_at: 900,
        closes_at: 1730,
        open_time: null,
        open_day: null,
        close_time: null,
        close_day: null,
      },
      {
        id: 3,
        day: 'Wednesday',
        opens_at: 900,
        closes_at: 1730,
        open_time: null,
        open_day: null,
        close_time: null,
        close_day: null,
      },
      {
        id: 2,
        day: 'Tuesday',
        opens_at: 1100,
        closes_at: 1930,
        open_time: null,
        open_day: null,
        close_time: null,
        close_day: null,
      },
      {
        id: 1,
        day: 'Monday',
        opens_at: 1100,
        closes_at: 1930,
        open_time: null,
        open_day: null,
        close_time: null,
        close_day: null,
      },
    ],
  },
  phones: [
    {
      id: 1,
      number: '(415) 565-7667',
      extension: null,
      service_type: '',
      country_code: 'US',
    },
  ],
  address: {
    id: 1,
    attention: null,
    name: null,
    address_1: '1748 Market St., Suite 201',
    address_2: null,
    address_3: null,
    address_4: null,
    city: 'San Francisco',
    state_province: 'CA',
    postal_code: '',
    country: 'USA',
    latitude: '37.7725604',
    longitude: '-122.4230558',
  },
  notes: [],
  categories: [
    {
      name: 'Medical',
      id: 3,
      top_level: true,
      featured: false,
    },
  ],
  ratings: [],
  recurringSchedule: {
    intervals: [
      {
        opensAt: {
          day: 1,
          hour: 11,
          minute: 0,
        },
        closesAt: {
          day: 1,
          hour: 19,
          minute: 30,
        },
      },
      {
        opensAt: {
          day: 2,
          hour: 11,
          minute: 0,
        },
        closesAt: {
          day: 2,
          hour: 19,
          minute: 30,
        },
      },
      {
        opensAt: {
          day: 3,
          hour: 9,
          minute: 0,
        },
        closesAt: {
          day: 3,
          hour: 17,
          minute: 30,
        },
      },
      {
        opensAt: {
          day: 4,
          hour: 9,
          minute: 0,
        },
        closesAt: {
          day: 4,
          hour: 17,
          minute: 30,
        },
      },
      {
        opensAt: {
          day: 5,
          hour: 9,
          minute: 0,
        },
        closesAt: {
          day: 5,
          hour: 17,
          minute: 30,
        },
      },
    ],
  },
};
